'use strict'

try{
    let x=10
    //x=10;
    //miFunction();
} catch(error){
    console.log(error);
} finally {
    console.log('termina la revisi√≥n de errores');
}
console.log('Continuamos..')